---
- name: check if node_exporter is already downloaded and installed
  stat:
    path: /usr/local/bin/node_exporter
    register: installed

- name: Download prometheus node_exporter from downloads website
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v"{{ exporter_version }}"/node_exporter-"{{ exporter_version }}".linux-amd64.tar.gz
    dest: /opt/
    mode: '0755'
  when: installed.stat.exists == false

- name: unarchive the node_exporter binary
  unarchive:
    src: /opt/node_exporter-"{{ exporter_version }}".linux-amd64.tar.gz
    dest: /opt/
    remote_src: yes
    mode: '0755'
  when: installed.stat.exists == false

- name: Add the user node_exporter
  user:
    name: node_exporter
    shell: /bin/false
    system: true

- name: writing systemd file for node_exporter
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/

- name: copy node_exporter to PATH
  copy:
    src: /opt/node_exporter-"{{ exporter_version }}".linux-amd64/node_exporter
    dest: /usr/local/bin/
    remote_src: yes
    owner: prometheus
    group: prometheus
  when: installed.stat.exists == false

- name: restart node_exporter
  service:
    name: node_exporter.service
    state: restarted
    daemon_reload: yes

- name: Check if node_exporter is functioning
  uri:
    url: http://localhost:9100
    method: GET
    status_code: 200
