---
- name: check if node_exporter is already downloaded and installed
  stat:
    path: /usr/local/bin/node_exporter
  register: installed

- name: Install prerequisites
  apt:
    name: libfontconfig1
    state: present
    update_cache: yes

- name: Download grafana latest debian package from download website and install
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_6.5.3_amd64.deb
  when: installed.stat.exists == false

- name: restart grafana service
  service:
    name: grafana-server.service
    state: restarted
    daemon_reload: yes

- name: Check if grafana is functioning
  uri:
    url: http://localhost:3000
    method: GET
    status_code: 200
