- name: Install and configure node-exporter with consul clients
  hosts: servers
  become: true
  user: ubuntu
  gather_facts: yes
  become_method: sudo
  vars_files:
   - group_vars/all
  roles:
   - role: consul-client
   - role: node-exporter
