- name: Install and configure nomad clients with consul
  hosts: clients
  become: true
  user: ubuntu
  gather_facts: yes
  become_method: sudo
  vars_files:
   - group_vars/all
  roles:
   - role: consul-client
   - role: nomad-client
