- name: Install and configure prometheus and grafana with consul clients
  hosts: servers
  become: true
  user: ubuntu
  gather_facts: yes
  become_method: sudo
  vars_files:
   - group_vars/all
  roles:
   - role: consul-client
   - role: prometheus
   - role: grafana
