---
classes: []
consul::datacenter: "%{::consul_dc}"
consul::discovery_max_stale: "1000ms"
consul::rpc_rate: 10000
consul::rpc_max_burst: 10000
consul::version: "1.5.3"
consul::daemon: "systemd"
consul::enterprise: true
datadog_agent::tags:
  - "env:%{::env}"
  - "cluster:%{::cluster_name}"
  - "multipaas_role:nomad_client"
nomad::acl: true
nomad::bin_dir: '/usr/bin'
nomad::log_level: 'DEBUG'
nomad::tls::enabled: true
nomad::vault_integration: true
nomad::version: '0.10.2'
splunk::hf::enabled: true
splunk::config::clientname: "%{::hostname}.%{::role}"
linkerd::logLevel: ALL
linkerd::env: "%{::env}"
linkerd::version: "1.7.0-27bae83"
trace_connector::image: dr.homeawaycorp.com/platformengineering/trace-connector:0.1.12
splunk::uf::version: "7.1.2"
splunk::hf::version: "7.1.0"
trelliumd::enabled: true
puppetrunner::enabled: false
limits::entries:
  'root/nofile':
    both: 131072
  'root/nproc':
    both: 268288
  'homeaway/nofile':
    both: 131072
  'homeaway/nproc':
    both: 268288
  '*/memlock':
    soft: 65536
    hard: 131072
newrelic::server::linux::newrelic_nrsysmond_manage_repo: false
newrelic::server::linux::newrelic_license_key: '172aa34b87fe8810c6019d29c216ada7f09870d0'
newrelic::server::linux::newrelic_nrsysmond_labels: "os:linux;puppet_env:%{::env}"
newrelic::server::linux::newrelic_nrsysmond_cgroup_style: '0'
rsyslog::server::expression_filters:
  hostname_filter:
    conditionals:
      if:
        expression: '$programname == "nomad"'
        tasks:
          - action:
              name: nomad_client
              type: omfile
              config:
                file: /var/log/nomad_client.log
          - stop: true
rsyslog::server::property_filters:
  consul_filter:
    property: 'syslogtag'
    operator: 'contains'
    value: 'consul'
    tasks:
      - action:
          name: consul
          type: omfile
          config:
            file: /var/log/consul.log
      - stop: true
  trelliumd_filter:
    property: 'syslogtag'
    operator: 'contains'
    value: 'trelliumd'
    tasks:
      - action:
          name: trelliumd
          type: omfile
          config:
            file: /var/log/trelliumd.log
      - stop: true
docker::version: "18.09.2"
docker::package: "docker-ce"
docker::ubuntu_version: "5:18.09.2~3-0~ubuntu-%{::lsbdistcodename}"
nomad::certs::common_name: "nomad-client.service.consul"
nomad::certs::alt_names:
  - "%{::fqdn}"
  - "%{::hostname}"
  - "localhost"
  - "nomad-client.service.%{::consul_dc}.consul"
  - "client.%{::nomad_region}.nomad"
  - "client.%{::region}.nomad"
  - "client.%{::region}-%{::env}.nomad"
  - "client.global.nomad"
nomad::certs::ip_sans:
  - "127.0.0.1"
  - "%{::ipaddress}"
vault_agent::enabled: true
vault_agent::version: "1.1.3"
vault_agent::enterprise: true
vault_agent::caching: true
vault_agent::listener::tcp::tls::disable: true
