---
- name: check if prometheus is already downloaded and installed
  stat:
    path: /usr/local/bin/prometheus
  register: installed

- name: Download prometheus source from downloads website
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /opt/
    mode: '0755'
  when: installed.stat.exists == false

- name: unarchive the prometheus source
  unarchive:
    src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /opt/
    remote_src: yes
    mode: '0755'
  when: installed.stat.exists == false

- name: Add the user prometheus
  user:
    name: prometheus
    shell: /bin/false
    home: /var/lib/prometheus
    system: true

- name: writing systemd file for prometheus
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/

- name: Create config and data directory
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: prometheus
    group: prometheus
  with_items:
    - /etc/prometheus
    - /var/lib/prometheus

- name: copy prometheus and promtool binary to PATH
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0755'
    owner: prometheus
    group: prometheus
  with_items:
    - "/opt/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
    - "/opt/prometheus-{{ prometheus_version }}.linux-amd64/promtool"
  when: installed.stat.exists == false

- name: copy consoles and console_libraries to /etc/prometheus
  copy:
    src: "{{ item }}"
    dest: /etc/prometheus
    remote_src: yes
    owner: prometheus
    group: prometheus
    directory_mode: yes
  with_items:
    - "/opt/prometheus-{{ prometheus_version }}.linux-amd64/consoles"
    - "/opt/prometheus-{{ prometheus_version }}.linux-amd64/console_libraries"
  when: installed.stat.exists == false

- name: Create prometheus.yml
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: '0640'
    owner: prometheus
    group: prometheus

- name: restart prometheus service
  service:
    name: prometheus.service
    state: restarted
    daemon_reload: yes

- name: Check if prometheus is functioning
  uri:
    url: http://localhost:9090
    method: GET
    status_code: 200
